interface SignUpFromMap {
  [key: string]: string;
}

export const SignUpFormApiMapper: SignUpFromMap = {
  CompanyName: 'cname',
  FedralTaxId: 'fedTaxId',
  PhoneNumber: 'phoneno',
  StateOfIncorporation: 'cstate',
  EstablishedYear: 'year',
  IndustrySelectedItems: 'industry',
  Division: 'division',
  Payroll: 'payroll',
  Specialization: 'area',
  TotalEmployees: 'noOfEmployees',
  TotalFullTimeEmployees: 'noOfFulltime',
  TotalSubContractors: 'noOfSubContractors',
  Worker: 'HWorkers',
  TotalH1BVisa: 'noOfVisa',
  Website: 'website',
  //USHeadQuarters: 'city',
  StreetAddress: 'address',
  City: 'city',
  State: 'state',
  Country: 'country',
  Zipcode: 'pincode',
  AName: 'fullname',
  Aemail: 'email',
  APhone: 'phone',
  BName: 'bname',
  BEmail: 'bemail',
  BPhone: 'bphone',
  TopTechSkills: 'topSkills',
  ServiceQualityPolicy: 'service',
  OfferTraining: 'training',
  BenefitsProvides: 'benefits',
  NIACSCode: 'naics',
  DnbRating: 'dnb',
  WForm: 'wForm',
  Articles: 'article',
  Certificate: 'goodStanding',
  Quaters: 'lastQuaters',
  Reason: 'reason',
  Name: 'repName',
  Title: 'repTitle',
  //Agree: 'repName',
};
